FLEET_HB_INTERVAL: 1 #與交管心跳的秒數
FLEET_HB_TIMEOUT: 3 #與交管心跳的秒

OTHER_HA_HB_INTERVAL: 1 #與交管心跳的秒數
OTHER_HA_HB_TIMEOUT: 3 #與交管心跳的秒

SERVER_IP: "localhost"
SERVER_PORT: "50052"

CLIENT_IP: "localhost"
CLIENT_PORT: "50053"

WEB_API_PORT: "50000"
